-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 14:33:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emprestimo-livro-modelo2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emprestimo-livro-modelo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emprestimo-livro-modelo2` DEFAULT CHARACTER SET utf8 ;
USE `emprestimo-livro-modelo2` ;

-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(55) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(55) NOT NULL,
  `numero` INT NOT NULL,
  `pendencia` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`editora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(55) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_editora_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(75) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `num_pg` INT NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `edicao` INT NOT NULL,
  `ano` YEAR NOT NULL,
  `is_emprestado` TINYINT NULL,
  `id_editora` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_livro_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_livro_editora1_idx` (`id_editora` ASC) VISIBLE,
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`id_editora`)
    REFERENCES `emprestimo-livro-modelo2`.`editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`emprestimo` (
  `id` INT NOT NULL,
  `dt_emprestimo` DATE NOT NULL,
  `dt_devolucao` DATE NULL,
  `multa` DECIMAL(2) NULL,
  `id_cliente` INT NOT NULL,
  `id_livro` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_emprestimo_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_emprestimo_livro1_idx` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `emprestimo-livro-modelo2`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `emprestimo-livro-modelo2`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`livro_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`livro_has_autor` (
  `id_livro` INT NOT NULL,
  `id_autor` INT NOT NULL,
  PRIMARY KEY (`id_livro`, `id_autor`),
  INDEX `fk_livro_has_autor_autor1_idx` (`id_autor` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro_idx` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_livro`
    FOREIGN KEY (`id_livro`)
    REFERENCES `emprestimo-livro-modelo2`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `emprestimo-livro-modelo2`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo-livro-modelo2`.`livro_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo-livro-modelo2`.`livro_has_genero` (
  `id_livro` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_livro`, `id_genero`),
  INDEX `fk_livro_has_genero_genero1_idx` (`id_genero` ASC) VISIBLE,
  INDEX `fk_livro_has_genero_livro1_idx` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_genero_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `emprestimo-livro-modelo2`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_genero_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `emprestimo-livro-modelo2`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
